# Generated by Django 4.2.1 on 2023-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('GPA', models.CharField(max_length=4)),
                ('level', models.CharField(max_length=1)),
                ('gender', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=10)),
                ('birth_day', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=20)),
            ],
        ),
    ]
