# Generated by Django 4.2.1 on 2023-05-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='departement',
            new_name='department',
        ),
    ]
